---
name: First Test workflow
on:
  - push
  - workflow_dispatch
env:
  UPSTREAM_VERSION: "8.0.5"
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Print UPSTREAM_VERSION
        run: echo "UPSTREAM_VERSION=$UPSTREAM_VERSION"
      - name: Download Suricata upstream tarball for given UPSTREAM_VERSION
        run: curl -O "https://www.openinfosecfoundation.org/download/suricata-$UPSTREAM_VERSION.tar.gz"
      - name: Calculate SHA256 hash of downloaded file
        run: sha256sum "suricata-$UPSTREAM_VERSION.tar.gz"
      # TODO: Verify download
      - run: ls -l
      - name: Upload upstream tarball as artifact
        uses: actions/upload-artifact@v7
        with:
          name: suricata-upstream
          path: "suricata-*.tar.gz"
          retention-days: 1
  build:
    needs: download
    strategy:
      fail-fast: false  # Do not cancel other matrix jobs when one job fails
      matrix:
        variant: [stable]
        distro: [bookworm, trixie]
        arch: [amd64]
    runs-on: ubuntu-latest
    container:
      image: debian:${{ matrix.distro }}
    env:
      DEBFULLNAME: GitHub CI/CD
      DEBEMAIL: noreply@example.com
    steps:
      - name: Print current build parameters
        run: |
          echo "suricata-$UPSTREAM_VERSION-${{ matrix.variant }} \
          for ${{ matrix.distro }} on ${{ matrix.arch }}"
          echo "DEBFULLNAME=$DEBFULLNAME"
          echo "DEBEMAIL=$DEBEMAIL"
      - run: cat /etc/debian_version
      - name: Download upstream tarball as artifact
        uses: actions/download-artifact@v8
        with:
          name: suricata-upstream
      - run: ls -la
      - name: Extract the upstream tarball
        run: |
          tar --extract --verbose --gunzip --directory ./
          --file "suricata-$UPSTREAM_VERSION.tar.gz"
      - run: ls -la
#       - uses: actions/checkout@v4
#
#       - name: Install build dependencies
#         run: |
#           apt-get update
#           apt-get install -y --no-install-recommends \
#             devscripts debhelper [...]
#
#       - name: Build
#         env:
#           OUTPUT_DIR: ${{ github.workspace }}/output
#         run: |
#           bash scripts/build-package.sh \
#             ${{ matrix.major_version }} \
#             ${{ inputs.upstream_version }} \
#             ${{ matrix.distro }} \
#             ${{ matrix.variant }}
#
#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: >-
#             deb-${{ matrix.major_version }}-${{ matrix.variant }}-
#             ${{ matrix.distro }}-${{ matrix.arch }}
#           path: output/*.deb
...
